### ISSUE TITLE
How fast is this compared to common ways for unpacking binaries?

### ISSUE THREAD

**Issue by lingeringwillx** [K0lb3/binaryreader#3]
I'm wondering if it would be worth it to write a C extension for this purpose, and your code seems to be the only attempt at this.

**Comment by K0lb3** [comment]
It depends a lot on the data.
If the data can be unpacked with more complex struct unpacks (e.g. multiple ints, floats and so on at once),
then this module is slower.

If the data contains strings of previously unknown lengths (e.g. encoded length, ending with \0), or in general some content that requires interaction and isn't static, then this module leaves struct in the dust.
